# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0858df3d2df7ad2cd65ed75bea834df80d4487ebd516cc79c855ba8e7dab75570d8df1a45cbb7d6cec55cb0c0d26c7c047afe05a17b30670074d8bb9b7f6278

test:
  secret_key_base: d676a1ee82016f54b4891bc0eb56a859f8001542c7c760c4c8cc89b5e9072546ae480ad4add7ef317652fd1f9a54592e1a1e5029aaaf6000931e227ab368ab08

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
